[general]
disable_reminders = false          # Set reminders on O_o events or not
verbosity_level = 1                # How much chatter to spill out when running sync 1 = errors only, 2 = info, 3 = debug
block_event_visibility = "private" # Keep O_o event public or private

[google]
client_id = ""     # Get these from the Google Developer Console
client_secret = "" # Get these from the Google Developer

[caldav]
url = ""      # URL of the CalDAV server
username = "" # Username for the CalDAV server
password = "" # Password for the CalDAV server

[office365]
client_id = ""     # Get these from the Azure Portal
client_secret = "" # Get these from the Azure Portal
tenant_id = ""     # Get these from the Azure Portal, make sure that the tenant has the correct permissions
